=== MarioTurrientes/Examen_3Lm/XML/XSD.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- ____________________________ELEMENTOS SIMPLES_____________________________-->
    <!-- definicion elementos strings-->
    <xs:simpleType name="strings">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <!-- definicion elemento temperatura max y min-->
    <xs:simpleType name="temperatura">
        <xs:restriction base="xs:int">
            <xs:pattern value="[0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- definicion elemento lluvia-->
    <xs:simpleType name="tipolluvia">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{2}%{1}"/> 
        </xs:restriction>
    </xs:simpleType>

    <!-- definicion elemento aviso-->
    <xs:simpleType name="aviso">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Viento"/>
            <xs:enumeration value="Nieve"/>
            <xs:enumeration value="Tormentas"/>
            <xs:enumeration value="Huracan"/>
        </xs:restriction>
    </xs:simpleType>

    <!--definicion elemento fecha-->
    <xs:simpleType name="year">
        <xs:restriction base="xs:date"/>
    </xs:simpleType>

    <!-- ____________________________ELEMENTOS COMPLEJOS_____________________________-->
    <!-- elemento poblacion-->
    <xs:element name="poblacion" type="tipopoblacion"/>

    <xs:complexType name="tipopoblacion">
        <xs:sequence>
            <xs:element name="nombre" type="strings" minOccurs="0" maxOccurs="1"/>
            <xs:element name="fecha" type="year"/>
            <xs:element name="temp_max" type="temperatura"/>
            <xs:element name="temp_min" type="temperatura"/>
            <xs:element name="lluvia" type="tipolluvia"/>
            <xs:element name="riesgo" type="aviso" minOccurs="0" maxOccurs="10"/> <!-- Pueden existir minimo 0 y maximo 10 como se indica-->
        </xs:sequence>
    </xs:complexType>

    <!-- elemento provincias-->
    <xs:element name="provincias" type="tipoprovincia"/>

    <xs:complexType name="tipoprovincia">
        <xs:sequence>
            <xs:element name="nombre" type="strings"/>
            <xs:element name="poblacion" type="tipopoblacion"/>
        </xs:sequence>
    </xs:complexType>

    <!-- elemento comunidad-->
    <xs:element name="comunidad" type="tipocomunidad"/>

    <xs:complexType name="tipocomunidad">
        <xs:sequence>
            <xs:element name="nombre" type="strings" minOccurs="1"/> <!--Puede o no existir-->
            <xs:element name="provincias" type="tipoprovincia"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- elemento general informacion-->
    <xs:element name="informacion" type="tipoinfo"/>

    <xs:complexType name="tipoinfo">
        <xs:sequence>
            <xs:element name="comunidad" type="tipocomunidad"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== MarioTurrientes/Examen_3Lm/XML/XML.xml
<?xml version="1.0" encoding="UTF-8"?>

<informacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="XSD.xsd">
    <comunidad><nombre>Andalucia</nombre>

        <provincias><nombre>Cadiz</nombre>

            <poblacion>
                <nombre>Alcobendas</nombre>
                <fecha>2017-03-21</fecha>
                <temp_max>40</temp_max>
                <temp_min>20</temp_min>
                <lluvia>30%</lluvia>
                <!-- Se eliminarÃ¡ el aviso porque asi lo indica-->
            </poblacion>

        </provincias>
        
    </comunidad>
</informacion>

=== MarioTurrientes/Examen_3Lm/XML/No_Valido.xml
<?xml version="1.0" encoding="UTF-8"?>

<informacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="XSD.xsd">
    <comunidad><nombre>Andalucia</nombre>

        <provincias><nombre>Cadiz</nombre>

            <poblacion>
                
                <fecha>2017-03-21</fecha>
                <temp_max>40</temp_max>
                <temp_min>20</temp_min>
                <lluvia>30%</lluvia>
                <riesgo>Viento</riesgo>
                <riesgo>Huracan</riesgo>
            </poblacion>

        </provincias>
        
    </comunidad>
</informacion>
